// <auto-generated />
using System;
using FinApp.Infrastructure.Expenses.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinApp.Infrastructure.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20211116215741_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinApp.Infrastructure.Expenses.Consumptions.ConsumptionTypeDbDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConsumptionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Name = "Prąd",
                            Unit = 0
                        },
                        new
                        {
                            Id = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Name = "Gaz",
                            Unit = 2
                        });
                });

            modelBuilder.Entity("FinApp.Infrastructure.Expenses.ExpenseDbDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConsumptionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumptionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionTypeId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2094c53-d3f9-4962-a726-ce6807478a70"),
                            ConsumptionAmount = 0m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 351, DateTimeKind.Local).AddTicks(6354),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 7, 11, 22, 40, 9, 0, DateTimeKind.Unspecified),
                            PaidAmount = 62.87m
                        },
                        new
                        {
                            Id = new Guid("9237c772-b038-44bb-8639-3ebd28b67acd"),
                            ConsumptionAmount = 0m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(4816),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 7, 12, 13, 4, 42, 0, DateTimeKind.Unspecified),
                            PaidAmount = 50.24m
                        },
                        new
                        {
                            Id = new Guid("a6d7caa6-7a60-498c-9bfb-860fa72dcef7"),
                            ConsumptionAmount = 3m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7040),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 8, 13, 13, 9, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 33.93m
                        },
                        new
                        {
                            Id = new Guid("c9b3c49d-35d0-4783-9d6c-365c6cfadf63"),
                            ConsumptionAmount = 9m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7142),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 9, 13, 15, 24, 36, 0, DateTimeKind.Unspecified),
                            PaidAmount = 37.25m
                        },
                        new
                        {
                            Id = new Guid("3eb1a0a6-ec9e-46f2-855b-6496c41a2259"),
                            ConsumptionAmount = 1m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7165),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 9, 18, 17, 51, 53, 0, DateTimeKind.Unspecified),
                            PaidAmount = 171m
                        },
                        new
                        {
                            Id = new Guid("91f744dd-8842-4789-97b1-31a1b9480565"),
                            ConsumptionAmount = 43m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7477),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 10, 15, 13, 7, 25, 0, DateTimeKind.Unspecified),
                            PaidAmount = 99m
                        },
                        new
                        {
                            Id = new Guid("103e3f64-1b11-4e72-a792-a70169bb12b4"),
                            ConsumptionAmount = 51m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7549),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 11, 11, 11, 6, 50, 0, DateTimeKind.Unspecified),
                            PaidAmount = 138.58m
                        },
                        new
                        {
                            Id = new Guid("36d40a9f-4617-4068-a95f-208e47088bba"),
                            ConsumptionAmount = 286m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7575),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 11, 19, 9, 36, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 193.56m
                        },
                        new
                        {
                            Id = new Guid("1789555f-d37d-421c-923c-e15c2797810b"),
                            ConsumptionAmount = 177m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7592),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 12, 11, 14, 20, 24, 0, DateTimeKind.Unspecified),
                            PaidAmount = 348.87m
                        },
                        new
                        {
                            Id = new Guid("10e45622-a147-48e6-a1fd-5c865a09835a"),
                            ConsumptionAmount = 405m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7626),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 1, 9, 16, 37, 29, 0, DateTimeKind.Unspecified),
                            PaidAmount = 261.98m
                        },
                        new
                        {
                            Id = new Guid("42307af4-22a9-41d5-8c0d-33ae5c345b1f"),
                            ConsumptionAmount = 180m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7650),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 1, 14, 13, 50, 55, 0, DateTimeKind.Unspecified),
                            PaidAmount = 354m
                        },
                        new
                        {
                            Id = new Guid("6b902a1f-c1af-49f5-98d3-35e26a1c3e0a"),
                            ConsumptionAmount = 202m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7664),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 2, 12, 15, 14, 11, 0, DateTimeKind.Unspecified),
                            PaidAmount = 388m
                        },
                        new
                        {
                            Id = new Guid("4480ae0c-e574-48c6-bcdf-aef92c0d0fe1"),
                            ConsumptionAmount = 171m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7678),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 3, 13, 13, 55, 33, 0, DateTimeKind.Unspecified),
                            PaidAmount = 330m
                        },
                        new
                        {
                            Id = new Guid("a0d0164e-3fb9-47e0-b6fe-db38ca60d36f"),
                            ConsumptionAmount = 610m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7701),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 3, 17, 13, 46, 23, 0, DateTimeKind.Unspecified),
                            PaidAmount = 409m
                        },
                        new
                        {
                            Id = new Guid("c488f798-78b8-4b01-bc90-dcab14c07ca7"),
                            ConsumptionAmount = 120m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7715),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 4, 15, 16, 35, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 239.15m
                        },
                        new
                        {
                            Id = new Guid("f56a8c0b-2c56-49ff-bb38-340540090031"),
                            ConsumptionAmount = 43m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7732),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 5, 13, 14, 19, 45, 0, DateTimeKind.Unspecified),
                            PaidAmount = 99.66m
                        },
                        new
                        {
                            Id = new Guid("be002e7d-6c59-435a-930f-f571a10fc031"),
                            ConsumptionAmount = 411m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7746),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 5, 13, 14, 22, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 293.21m
                        },
                        new
                        {
                            Id = new Guid("8b5f22d6-5714-4c66-8fea-90e2a088bbb0"),
                            ConsumptionAmount = 26m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7762),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 6, 15, 13, 13, 37, 0, DateTimeKind.Unspecified),
                            PaidAmount = 68m
                        },
                        new
                        {
                            Id = new Guid("cd87bfd4-052f-4a99-9a9d-e820dc088ed2"),
                            ConsumptionAmount = 376m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7775),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 7, 14, 11, 43, 59, 0, DateTimeKind.Unspecified),
                            PaidAmount = 270m
                        },
                        new
                        {
                            Id = new Guid("7d4583bb-ff0f-4e46-978d-51f2ff4e06ba"),
                            ConsumptionAmount = 15m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7799),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 7, 14, 16, 43, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 47m
                        },
                        new
                        {
                            Id = new Guid("e4a27d5d-62db-45a6-8be7-2b6350a7b4c6"),
                            ConsumptionAmount = 14m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7832),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 8, 14, 12, 18, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 45m
                        },
                        new
                        {
                            Id = new Guid("f817a815-c10a-4326-8306-5ec011f6d17a"),
                            ConsumptionAmount = 381m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7873),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 9, 9, 9, 20, 5, 0, DateTimeKind.Unspecified),
                            PaidAmount = 273.24m
                        },
                        new
                        {
                            Id = new Guid("3b043286-8507-4700-98ac-b77fb3f4f84d"),
                            ConsumptionAmount = 30m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7910),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 9, 30, 15, 28, 29, 0, DateTimeKind.Unspecified),
                            PaidAmount = 77.55m
                        },
                        new
                        {
                            Id = new Guid("0c0e217f-52a3-435d-8e1f-f4d274258914"),
                            ConsumptionAmount = 19m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7925),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 10, 21, 19, 46, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 47.18m
                        },
                        new
                        {
                            Id = new Guid("cfeaeb6c-f9e2-4cb5-a172-649553ec02c8"),
                            ConsumptionAmount = 474m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7961),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 11, 6, 7, 34, 13, 0, DateTimeKind.Unspecified),
                            PaidAmount = 332.81m
                        },
                        new
                        {
                            Id = new Guid("b89d05b5-c976-494e-99ac-2d04abfeaff9"),
                            ConsumptionAmount = 129m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7983),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 11, 17, 15, 27, 21, 0, DateTimeKind.Unspecified),
                            PaidAmount = 240m
                        },
                        new
                        {
                            Id = new Guid("40135451-be5f-4f99-8dae-f89a60d2c3c8"),
                            ConsumptionAmount = 156m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(7996),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 12, 17, 16, 49, 6, 0, DateTimeKind.Unspecified),
                            PaidAmount = 282.76m
                        },
                        new
                        {
                            Id = new Guid("1c01016f-45c6-4dc0-b347-7b54b847fb29"),
                            ConsumptionAmount = 668m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8011),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 1, 15, 21, 42, 42, 0, DateTimeKind.Unspecified),
                            PaidAmount = 490m
                        },
                        new
                        {
                            Id = new Guid("667ce6e5-1ecd-4d86-9d7d-b2d03be781bd"),
                            ConsumptionAmount = 193m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8025),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 1, 18, 22, 35, 50, 0, DateTimeKind.Unspecified),
                            PaidAmount = 343m
                        },
                        new
                        {
                            Id = new Guid("6e8f8248-093f-4bdc-ab49-28b153460132"),
                            ConsumptionAmount = 231m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8044),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 2, 16, 14, 13, 9, 0, DateTimeKind.Unspecified),
                            PaidAmount = 401.13m
                        },
                        new
                        {
                            Id = new Guid("1eb36a4c-5ab3-4549-a0ed-c199937e0f2b"),
                            ConsumptionAmount = 613m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8075),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 3, 11, 17, 23, 40, 0, DateTimeKind.Unspecified),
                            PaidAmount = 452.38m
                        },
                        new
                        {
                            Id = new Guid("7774e1ff-1c01-4423-a954-0699eee76de5"),
                            ConsumptionAmount = 176m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8111),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 3, 17, 19, 36, 57, 0, DateTimeKind.Unspecified),
                            PaidAmount = 311m
                        },
                        new
                        {
                            Id = new Guid("1bf588fa-ea43-459c-bcae-84c775ff2c86"),
                            ConsumptionAmount = 140m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8124),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 4, 16, 19, 9, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 250m
                        },
                        new
                        {
                            Id = new Guid("2d5e7915-e9af-4090-b651-04030c4344f0"),
                            ConsumptionAmount = 550m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8143),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 5, 11, 22, 21, 8, 0, DateTimeKind.Unspecified),
                            PaidAmount = 410m
                        },
                        new
                        {
                            Id = new Guid("f2065da0-96f7-4441-9c8c-351ac2ea89ee"),
                            ConsumptionAmount = 91m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8170),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 5, 14, 6, 44, 10, 0, DateTimeKind.Unspecified),
                            PaidAmount = 193m
                        },
                        new
                        {
                            Id = new Guid("572a554b-6f13-4d3d-9f0c-e458a448989b"),
                            ConsumptionAmount = 29m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8183),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 6, 16, 17, 38, 39, 0, DateTimeKind.Unspecified),
                            PaidAmount = 70.79m
                        },
                        new
                        {
                            Id = new Guid("257d973f-1d85-4237-90c9-6a4c33a585c4"),
                            ConsumptionAmount = 321m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8203),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 7, 12, 19, 21, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 266.71m
                        },
                        new
                        {
                            Id = new Guid("cd7fc464-cf6d-4814-8f97-0ceded261add"),
                            ConsumptionAmount = 18m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8232),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 7, 14, 20, 38, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 51.97m
                        },
                        new
                        {
                            Id = new Guid("a1ee9473-4e54-4577-8d61-a66dcd322516"),
                            ConsumptionAmount = 18m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8256),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 8, 17, 10, 8, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 52.55m
                        },
                        new
                        {
                            Id = new Guid("30fe4931-8c35-4aff-a877-811152b22b90"),
                            ConsumptionAmount = 356m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8271),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 9, 9, 21, 29, 21, 0, DateTimeKind.Unspecified),
                            PaidAmount = 285m
                        },
                        new
                        {
                            Id = new Guid("3bc5ecdf-1c7a-4b2d-b628-899750a7faa2"),
                            ConsumptionAmount = 77m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8284),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 10, 20, 17, 27, 53, 0, DateTimeKind.Unspecified),
                            PaidAmount = 168m
                        },
                        new
                        {
                            Id = new Guid("4ca2b533-c097-42d2-afbf-babcabd4aa52"),
                            ConsumptionAmount = 413m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8300),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 11, 6, 15, 41, 24, 0, DateTimeKind.Unspecified),
                            PaidAmount = 321.84m
                        },
                        new
                        {
                            Id = new Guid("50e87df6-dc86-4562-8289-398d4bc5aa1a"),
                            ConsumptionAmount = 20m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            CreatedAt = new DateTime(2021, 11, 16, 22, 57, 40, 374, DateTimeKind.Local).AddTicks(8331),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 9, 10, 15, 55, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 58.35m
                        });
                });

            modelBuilder.Entity("FinApp.Infrastructure.Expenses.ExpenseDbDto", b =>
                {
                    b.HasOne("FinApp.Infrastructure.Expenses.Consumptions.ConsumptionTypeDbDto", "ConsumptionType")
                        .WithMany()
                        .HasForeignKey("ConsumptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumptionType");
                });
#pragma warning restore 612, 618
        }
    }
}
