// <auto-generated />
using System;
using FinApp.Infrastructure.Expenses.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinApp.Infrastructure.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    partial class ExpensesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinApp.Infrastructure.Expenses.Consumptions.ConsumptionTypeDbDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConsumptionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Name = "Prąd",
                            Unit = 0
                        },
                        new
                        {
                            Id = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Name = "Gaz",
                            Unit = 2
                        });
                });

            modelBuilder.Entity("FinApp.Infrastructure.Expenses.ExpenseDbDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConsumptionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumptionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionTypeId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39b8a901-ab7d-47df-8a38-48e855727339"),
                            ConsumptionAmount = 0m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 7, 11, 22, 40, 9, 0, DateTimeKind.Unspecified),
                            PaidAmount = 62.87m
                        },
                        new
                        {
                            Id = new Guid("8c7b9088-ed5b-4a38-ae5a-1e74b5d8f5c1"),
                            ConsumptionAmount = 0m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 7, 12, 13, 4, 42, 0, DateTimeKind.Unspecified),
                            PaidAmount = 50.24m
                        },
                        new
                        {
                            Id = new Guid("c806c592-4b0a-4854-90cb-6e6cd80550be"),
                            ConsumptionAmount = 3m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 8, 13, 13, 9, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 33.93m
                        },
                        new
                        {
                            Id = new Guid("f219efcd-c2a8-4f54-8041-97e22f1ba7e6"),
                            ConsumptionAmount = 9m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 9, 13, 15, 24, 36, 0, DateTimeKind.Unspecified),
                            PaidAmount = 37.25m
                        },
                        new
                        {
                            Id = new Guid("6bd08013-5560-4f45-965b-75f17f1e0488"),
                            ConsumptionAmount = 1m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 9, 18, 17, 51, 53, 0, DateTimeKind.Unspecified),
                            PaidAmount = 171m
                        },
                        new
                        {
                            Id = new Guid("c97c5e85-9d7a-4b83-86e6-734c686ea908"),
                            ConsumptionAmount = 43m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 10, 15, 13, 7, 25, 0, DateTimeKind.Unspecified),
                            PaidAmount = 99m
                        },
                        new
                        {
                            Id = new Guid("dadd04c4-f7da-4449-9ee6-153dcb04ab5c"),
                            ConsumptionAmount = 51m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 11, 11, 11, 6, 50, 0, DateTimeKind.Unspecified),
                            PaidAmount = 138.58m
                        },
                        new
                        {
                            Id = new Guid("5cd97768-d804-4db6-98aa-65df16b7974f"),
                            ConsumptionAmount = 286m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 11, 19, 9, 36, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 193.56m
                        },
                        new
                        {
                            Id = new Guid("86506ae5-9c68-4bd7-b3b3-7fe636c60714"),
                            ConsumptionAmount = 177m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 12, 11, 14, 20, 24, 0, DateTimeKind.Unspecified),
                            PaidAmount = 348.87m
                        },
                        new
                        {
                            Id = new Guid("f426dda3-a95f-4a3e-9aee-1a1e422b2c6b"),
                            ConsumptionAmount = 405m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 1, 9, 16, 37, 29, 0, DateTimeKind.Unspecified),
                            PaidAmount = 261.98m
                        },
                        new
                        {
                            Id = new Guid("5303e239-4a95-416b-b930-377826553386"),
                            ConsumptionAmount = 180m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 1, 14, 13, 50, 55, 0, DateTimeKind.Unspecified),
                            PaidAmount = 354m
                        },
                        new
                        {
                            Id = new Guid("d4e5d79a-c4a8-42dd-ba8f-57544ac49738"),
                            ConsumptionAmount = 202m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 2, 12, 15, 14, 11, 0, DateTimeKind.Unspecified),
                            PaidAmount = 388m
                        },
                        new
                        {
                            Id = new Guid("0300ba68-13e6-4a48-aacb-20b9e2c864b2"),
                            ConsumptionAmount = 171m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 3, 13, 13, 55, 33, 0, DateTimeKind.Unspecified),
                            PaidAmount = 330m
                        },
                        new
                        {
                            Id = new Guid("088e908c-3d91-42af-bfdd-24b0db8fdf62"),
                            ConsumptionAmount = 610m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 3, 17, 13, 46, 23, 0, DateTimeKind.Unspecified),
                            PaidAmount = 409m
                        },
                        new
                        {
                            Id = new Guid("104f34a1-562b-433c-be00-3c3b254b86c2"),
                            ConsumptionAmount = 120m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 4, 15, 16, 35, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 239.15m
                        },
                        new
                        {
                            Id = new Guid("5f3fa8ee-6420-453a-ad62-8414da4d046c"),
                            ConsumptionAmount = 43m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 5, 13, 14, 19, 45, 0, DateTimeKind.Unspecified),
                            PaidAmount = 99.66m
                        },
                        new
                        {
                            Id = new Guid("42f55ea8-2618-461a-83be-0a8e827ab0c6"),
                            ConsumptionAmount = 411m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 5, 13, 14, 22, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 293.21m
                        },
                        new
                        {
                            Id = new Guid("2a696a58-f594-4ff3-ba25-608b0b1ca766"),
                            ConsumptionAmount = 26m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 6, 15, 13, 13, 37, 0, DateTimeKind.Unspecified),
                            PaidAmount = 68m
                        },
                        new
                        {
                            Id = new Guid("aabc1cc1-b821-4c8d-9da0-de706358963b"),
                            ConsumptionAmount = 376m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 7, 14, 11, 43, 59, 0, DateTimeKind.Unspecified),
                            PaidAmount = 270m
                        },
                        new
                        {
                            Id = new Guid("02e32908-340a-4974-98c0-ce57a48d552c"),
                            ConsumptionAmount = 15m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 7, 14, 16, 43, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 47m
                        },
                        new
                        {
                            Id = new Guid("f2f12d36-072e-48c5-a94d-f5af9e69f009"),
                            ConsumptionAmount = 14m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 8, 14, 12, 18, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 45m
                        },
                        new
                        {
                            Id = new Guid("f840d2f3-1b02-4172-b770-d8cb7f5db036"),
                            ConsumptionAmount = 381m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 9, 9, 9, 20, 5, 0, DateTimeKind.Unspecified),
                            PaidAmount = 273.24m
                        },
                        new
                        {
                            Id = new Guid("9ea32c9e-809e-47aa-ada3-caaeeb3229bb"),
                            ConsumptionAmount = 30m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 9, 30, 15, 28, 29, 0, DateTimeKind.Unspecified),
                            PaidAmount = 77.55m
                        },
                        new
                        {
                            Id = new Guid("f7a75595-9edd-40fd-97e5-9ff25f1fac8f"),
                            ConsumptionAmount = 19m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 10, 21, 19, 46, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 47.18m
                        },
                        new
                        {
                            Id = new Guid("ea737911-afaf-482d-aced-974a120aaeb9"),
                            ConsumptionAmount = 474m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 11, 6, 7, 34, 13, 0, DateTimeKind.Unspecified),
                            PaidAmount = 332.81m
                        },
                        new
                        {
                            Id = new Guid("af2b9d4c-a007-4038-ac6e-950ed4e4d62f"),
                            ConsumptionAmount = 129m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 11, 17, 15, 27, 21, 0, DateTimeKind.Unspecified),
                            PaidAmount = 240m
                        },
                        new
                        {
                            Id = new Guid("ae99d25c-cc0f-4284-b3f6-1a53c0ee0325"),
                            ConsumptionAmount = 156m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 12, 17, 16, 49, 6, 0, DateTimeKind.Unspecified),
                            PaidAmount = 282.76m
                        },
                        new
                        {
                            Id = new Guid("08d9d49f-a02f-427d-809c-24fdeb8a8509"),
                            ConsumptionAmount = 668m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 1, 15, 21, 42, 42, 0, DateTimeKind.Unspecified),
                            PaidAmount = 490m
                        },
                        new
                        {
                            Id = new Guid("1f5d4b7f-33ca-4dc0-a9d0-ebaa9eb109ed"),
                            ConsumptionAmount = 193m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 1, 18, 22, 35, 50, 0, DateTimeKind.Unspecified),
                            PaidAmount = 343m
                        },
                        new
                        {
                            Id = new Guid("3fcb0710-63be-4380-b2bc-ef7629a95ada"),
                            ConsumptionAmount = 231m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 2, 16, 14, 13, 9, 0, DateTimeKind.Unspecified),
                            PaidAmount = 401.13m
                        },
                        new
                        {
                            Id = new Guid("b893e394-2352-430f-8589-d3138b77acb2"),
                            ConsumptionAmount = 613m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 3, 11, 17, 23, 40, 0, DateTimeKind.Unspecified),
                            PaidAmount = 452.38m
                        },
                        new
                        {
                            Id = new Guid("ad9f0e84-52ac-4f16-9d28-892baafa4719"),
                            ConsumptionAmount = 176m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 3, 17, 19, 36, 57, 0, DateTimeKind.Unspecified),
                            PaidAmount = 311m
                        },
                        new
                        {
                            Id = new Guid("0d526e0d-0430-4172-a5e0-12e2e32560fe"),
                            ConsumptionAmount = 140m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 4, 16, 19, 9, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 250m
                        },
                        new
                        {
                            Id = new Guid("908396e8-ca95-436e-be19-401c5f53068a"),
                            ConsumptionAmount = 550m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 5, 11, 22, 21, 8, 0, DateTimeKind.Unspecified),
                            PaidAmount = 410m
                        },
                        new
                        {
                            Id = new Guid("57650974-3d2f-4f9e-972b-b1551270b1f1"),
                            ConsumptionAmount = 91m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 5, 14, 6, 44, 10, 0, DateTimeKind.Unspecified),
                            PaidAmount = 193m
                        },
                        new
                        {
                            Id = new Guid("33eb2ff3-3607-4a93-a29e-38f1803b0a22"),
                            ConsumptionAmount = 29m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 6, 16, 17, 38, 39, 0, DateTimeKind.Unspecified),
                            PaidAmount = 70.79m
                        },
                        new
                        {
                            Id = new Guid("0c75d48f-2a1e-4f89-ba3e-2c6b1abefe35"),
                            ConsumptionAmount = 321m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 7, 12, 19, 21, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 266.71m
                        },
                        new
                        {
                            Id = new Guid("348d5a8e-8e7c-48b6-8a17-5eec1eeb7e31"),
                            ConsumptionAmount = 18m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 7, 14, 20, 38, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 51.97m
                        },
                        new
                        {
                            Id = new Guid("58ccfde8-25ec-47b9-a164-ee31fd5b20dc"),
                            ConsumptionAmount = 18m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 8, 17, 10, 8, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 52.55m
                        },
                        new
                        {
                            Id = new Guid("dd421b7d-50f6-4fac-b012-c025da13b461"),
                            ConsumptionAmount = 356m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 9, 9, 21, 29, 21, 0, DateTimeKind.Unspecified),
                            PaidAmount = 285m
                        },
                        new
                        {
                            Id = new Guid("044abbff-5b54-4a8c-b1d0-9019adaef24a"),
                            ConsumptionAmount = 77m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 10, 20, 17, 27, 53, 0, DateTimeKind.Unspecified),
                            PaidAmount = 168m
                        },
                        new
                        {
                            Id = new Guid("def3280d-e3d1-478d-b6ba-b178292fa879"),
                            ConsumptionAmount = 413m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 11, 6, 15, 41, 24, 0, DateTimeKind.Unspecified),
                            PaidAmount = 321.84m
                        },
                        new
                        {
                            Id = new Guid("12cfb3af-b673-43e0-82c5-5e7cd1a51892"),
                            ConsumptionAmount = 20m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 9, 10, 15, 55, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 58.35m
                        });
                });

            modelBuilder.Entity("FinApp.Infrastructure.Expenses.ExpenseDbDto", b =>
                {
                    b.HasOne("FinApp.Infrastructure.Expenses.Consumptions.ConsumptionTypeDbDto", "ConsumptionType")
                        .WithMany()
                        .HasForeignKey("ConsumptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumptionType");
                });
#pragma warning restore 612, 618
        }
    }
}
