// <auto-generated />
using System;
using FinApp.Api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinApp.Api.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20211120190657_ModelValidationRules")]
    partial class ModelValidationRules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinApp.Api.Models.ConsumptionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("ConsumptionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Name = "Prąd",
                            Unit = "kWh"
                        },
                        new
                        {
                            Id = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Name = "Gaz",
                            Unit = "m3"
                        });
                });

            modelBuilder.Entity("FinApp.Api.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConsumptionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ConsumptionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionTypeId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9f99629-9644-40ec-8aab-d0fdcbe1f916"),
                            ConsumptionAmount = 0m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 7, 11, 22, 40, 9, 0, DateTimeKind.Unspecified),
                            PaidAmount = 62.87m
                        },
                        new
                        {
                            Id = new Guid("d01390fa-107e-4fe4-b954-bc9e93b80db6"),
                            ConsumptionAmount = 0m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 7, 12, 13, 4, 42, 0, DateTimeKind.Unspecified),
                            PaidAmount = 50.24m
                        },
                        new
                        {
                            Id = new Guid("f0ccfd18-e6d8-4f3c-a4e6-704aa664e594"),
                            ConsumptionAmount = 3m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 8, 13, 13, 9, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 33.93m
                        },
                        new
                        {
                            Id = new Guid("26f364b9-5113-4653-b133-7d8e8c230734"),
                            ConsumptionAmount = 9m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 9, 13, 15, 24, 36, 0, DateTimeKind.Unspecified),
                            PaidAmount = 37.25m
                        },
                        new
                        {
                            Id = new Guid("151459fe-4166-4f6d-9e2c-943915227f56"),
                            ConsumptionAmount = 1m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 9, 18, 17, 51, 53, 0, DateTimeKind.Unspecified),
                            PaidAmount = 171m
                        },
                        new
                        {
                            Id = new Guid("fd8543e9-22c1-485e-a8e7-f496317633ae"),
                            ConsumptionAmount = 43m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 10, 15, 13, 7, 25, 0, DateTimeKind.Unspecified),
                            PaidAmount = 99m
                        },
                        new
                        {
                            Id = new Guid("9c99bebe-6bc9-4d26-b385-3c6622145bc2"),
                            ConsumptionAmount = 51m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 11, 11, 11, 6, 50, 0, DateTimeKind.Unspecified),
                            PaidAmount = 138.58m
                        },
                        new
                        {
                            Id = new Guid("59d10272-f298-473c-8ce8-44710177237a"),
                            ConsumptionAmount = 286m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 11, 19, 9, 36, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 193.56m
                        },
                        new
                        {
                            Id = new Guid("6e0cceea-bb63-4a15-bb5c-13a679cc6105"),
                            ConsumptionAmount = 177m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 12, 11, 14, 20, 24, 0, DateTimeKind.Unspecified),
                            PaidAmount = 348.87m
                        },
                        new
                        {
                            Id = new Guid("4cec931d-c366-4f5f-9b20-e94b561a7386"),
                            ConsumptionAmount = 405m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 1, 9, 16, 37, 29, 0, DateTimeKind.Unspecified),
                            PaidAmount = 261.98m
                        },
                        new
                        {
                            Id = new Guid("5055f548-51da-4899-bc02-89f44f83dc00"),
                            ConsumptionAmount = 180m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 1, 14, 13, 50, 55, 0, DateTimeKind.Unspecified),
                            PaidAmount = 354m
                        },
                        new
                        {
                            Id = new Guid("b2fdc651-2675-4bcc-89cf-b21f1e444a61"),
                            ConsumptionAmount = 202m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 2, 12, 15, 14, 11, 0, DateTimeKind.Unspecified),
                            PaidAmount = 388m
                        },
                        new
                        {
                            Id = new Guid("c5e08d51-2d4e-44fd-95ac-0f38c5b4744a"),
                            ConsumptionAmount = 171m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 3, 13, 13, 55, 33, 0, DateTimeKind.Unspecified),
                            PaidAmount = 330m
                        },
                        new
                        {
                            Id = new Guid("131cde3c-8e1c-4295-b41a-78e8b655b5d8"),
                            ConsumptionAmount = 610m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 3, 17, 13, 46, 23, 0, DateTimeKind.Unspecified),
                            PaidAmount = 409m
                        },
                        new
                        {
                            Id = new Guid("524d83c4-4504-4549-be84-8599ae9ef072"),
                            ConsumptionAmount = 120m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 4, 15, 16, 35, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 239.15m
                        },
                        new
                        {
                            Id = new Guid("7a9a998c-7c6d-4024-bc13-0d958bc3a487"),
                            ConsumptionAmount = 43m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 5, 13, 14, 19, 45, 0, DateTimeKind.Unspecified),
                            PaidAmount = 99.66m
                        },
                        new
                        {
                            Id = new Guid("2cf4302c-b20c-4315-8ae4-32fc537ca8d7"),
                            ConsumptionAmount = 411m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 5, 13, 14, 22, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 293.21m
                        },
                        new
                        {
                            Id = new Guid("d904042e-8dd0-4dde-b0d0-8ff3982d558f"),
                            ConsumptionAmount = 26m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 6, 15, 13, 13, 37, 0, DateTimeKind.Unspecified),
                            PaidAmount = 68m
                        },
                        new
                        {
                            Id = new Guid("f6b05c0c-1e42-4a28-8270-d88a9010d9cf"),
                            ConsumptionAmount = 376m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 7, 14, 11, 43, 59, 0, DateTimeKind.Unspecified),
                            PaidAmount = 270m
                        },
                        new
                        {
                            Id = new Guid("25bbe355-7fa3-470f-90d4-9d32f94a5db7"),
                            ConsumptionAmount = 15m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 7, 14, 16, 43, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 47m
                        },
                        new
                        {
                            Id = new Guid("5af1f6fa-a6fc-4f31-a283-df99076642d0"),
                            ConsumptionAmount = 14m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 8, 14, 12, 18, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 45m
                        },
                        new
                        {
                            Id = new Guid("451c5376-536e-42be-bce4-6f135c12dafd"),
                            ConsumptionAmount = 381m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 9, 9, 9, 20, 5, 0, DateTimeKind.Unspecified),
                            PaidAmount = 273.24m
                        },
                        new
                        {
                            Id = new Guid("476b185c-dd9b-4eba-9afe-7f1cd187b0ec"),
                            ConsumptionAmount = 30m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 9, 30, 15, 28, 29, 0, DateTimeKind.Unspecified),
                            PaidAmount = 77.55m
                        },
                        new
                        {
                            Id = new Guid("2f26337c-3175-43c4-8171-32e8b751571b"),
                            ConsumptionAmount = 19m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 10, 21, 19, 46, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 47.18m
                        },
                        new
                        {
                            Id = new Guid("46d98023-e88e-47d9-b59f-1629eb4c8b0f"),
                            ConsumptionAmount = 474m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 11, 6, 7, 34, 13, 0, DateTimeKind.Unspecified),
                            PaidAmount = 332.81m
                        },
                        new
                        {
                            Id = new Guid("e216ba1d-16a3-4b8c-85bb-0ff20156111f"),
                            ConsumptionAmount = 129m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 11, 17, 15, 27, 21, 0, DateTimeKind.Unspecified),
                            PaidAmount = 240m
                        },
                        new
                        {
                            Id = new Guid("78f41df5-5ddd-4993-b83e-e3bd5c7e4ffc"),
                            ConsumptionAmount = 156m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 12, 17, 16, 49, 6, 0, DateTimeKind.Unspecified),
                            PaidAmount = 282.76m
                        },
                        new
                        {
                            Id = new Guid("46df2de9-d260-4197-bbf7-0b84fa294963"),
                            ConsumptionAmount = 668m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 1, 15, 21, 42, 42, 0, DateTimeKind.Unspecified),
                            PaidAmount = 490m
                        },
                        new
                        {
                            Id = new Guid("72ee4461-b3af-447e-954b-1ee623afb5d0"),
                            ConsumptionAmount = 193m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 1, 18, 22, 35, 50, 0, DateTimeKind.Unspecified),
                            PaidAmount = 343m
                        },
                        new
                        {
                            Id = new Guid("4f3e60ea-d094-4774-af0d-b7fb4c0add5f"),
                            ConsumptionAmount = 231m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 2, 16, 14, 13, 9, 0, DateTimeKind.Unspecified),
                            PaidAmount = 401.13m
                        },
                        new
                        {
                            Id = new Guid("e2887792-629a-4717-9214-3626342f2c76"),
                            ConsumptionAmount = 613m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 3, 11, 17, 23, 40, 0, DateTimeKind.Unspecified),
                            PaidAmount = 452.38m
                        },
                        new
                        {
                            Id = new Guid("de2c2bd2-9b5c-40a6-aab9-696c2d5f1da8"),
                            ConsumptionAmount = 176m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 3, 17, 19, 36, 57, 0, DateTimeKind.Unspecified),
                            PaidAmount = 311m
                        },
                        new
                        {
                            Id = new Guid("044b0634-5dc7-4ec5-b32e-bd23331f0d15"),
                            ConsumptionAmount = 140m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 4, 16, 19, 9, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 250m
                        },
                        new
                        {
                            Id = new Guid("ecc44f8a-b4b0-41c6-aea5-8b33f8493ca6"),
                            ConsumptionAmount = 550m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 5, 11, 22, 21, 8, 0, DateTimeKind.Unspecified),
                            PaidAmount = 410m
                        },
                        new
                        {
                            Id = new Guid("f0e2da91-ab42-4397-96c1-e1017b434aba"),
                            ConsumptionAmount = 91m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 5, 14, 6, 44, 10, 0, DateTimeKind.Unspecified),
                            PaidAmount = 193m
                        },
                        new
                        {
                            Id = new Guid("1bc5f4b2-face-4f57-9064-84ba80c66e08"),
                            ConsumptionAmount = 29m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 6, 16, 17, 38, 39, 0, DateTimeKind.Unspecified),
                            PaidAmount = 70.79m
                        },
                        new
                        {
                            Id = new Guid("ffa56ec2-1ba6-4519-a206-0e36659d9b6a"),
                            ConsumptionAmount = 321m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 7, 12, 19, 21, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 266.71m
                        },
                        new
                        {
                            Id = new Guid("95391898-43d8-4e12-9abc-e48bd84ca85f"),
                            ConsumptionAmount = 18m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 7, 14, 20, 38, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 51.97m
                        },
                        new
                        {
                            Id = new Guid("07ec3b91-4c88-4d08-9e05-bb154f833d08"),
                            ConsumptionAmount = 18m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 8, 17, 10, 8, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 52.55m
                        },
                        new
                        {
                            Id = new Guid("42939423-36c8-44da-b35e-a4c672cd6862"),
                            ConsumptionAmount = 356m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 9, 9, 21, 29, 21, 0, DateTimeKind.Unspecified),
                            PaidAmount = 285m
                        },
                        new
                        {
                            Id = new Guid("d18c970f-b577-4a9a-b557-d6eea55557de"),
                            ConsumptionAmount = 77m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 10, 20, 17, 27, 53, 0, DateTimeKind.Unspecified),
                            PaidAmount = 168m
                        },
                        new
                        {
                            Id = new Guid("56070bea-5074-4b55-86c6-6fcc42e1a7a5"),
                            ConsumptionAmount = 413m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 11, 6, 15, 41, 24, 0, DateTimeKind.Unspecified),
                            PaidAmount = 321.84m
                        },
                        new
                        {
                            Id = new Guid("359f71e0-d126-4181-9053-fcf645a76e4e"),
                            ConsumptionAmount = 20m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 9, 10, 15, 55, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 58.35m
                        });
                });

            modelBuilder.Entity("FinApp.Api.Models.Expense", b =>
                {
                    b.HasOne("FinApp.Api.Models.ConsumptionType", "ConsumptionType")
                        .WithMany()
                        .HasForeignKey("ConsumptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumptionType");
                });
#pragma warning restore 612, 618
        }
    }
}
