// <auto-generated />
using System;
using FinApp.Api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinApp.Api.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20211118160719_ChangedUnitToString")]
    partial class ChangedUnitToString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinApp.Api.Models.ConsumptionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsumptionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Name = "Prąd",
                            Unit = "kWh"
                        },
                        new
                        {
                            Id = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Name = "Gaz",
                            Unit = "m3"
                        });
                });

            modelBuilder.Entity("FinApp.Api.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConsumptionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ConsumptionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionTypeId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5032d4f-64be-47bf-b86e-87acf9b5f2e1"),
                            ConsumptionAmount = 0m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 7, 11, 22, 40, 9, 0, DateTimeKind.Unspecified),
                            PaidAmount = 62.87m
                        },
                        new
                        {
                            Id = new Guid("8addf195-f0fe-48fd-97bd-d910208f6249"),
                            ConsumptionAmount = 0m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 7, 12, 13, 4, 42, 0, DateTimeKind.Unspecified),
                            PaidAmount = 50.24m
                        },
                        new
                        {
                            Id = new Guid("ba11721c-9a9b-4341-a849-1fe2efd7f016"),
                            ConsumptionAmount = 3m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 8, 13, 13, 9, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 33.93m
                        },
                        new
                        {
                            Id = new Guid("d3eaf6a0-0a23-4b01-9495-37f6b950dff2"),
                            ConsumptionAmount = 9m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 9, 13, 15, 24, 36, 0, DateTimeKind.Unspecified),
                            PaidAmount = 37.25m
                        },
                        new
                        {
                            Id = new Guid("b56867f3-8372-4f23-92c7-c8a818a6e9cf"),
                            ConsumptionAmount = 1m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 9, 18, 17, 51, 53, 0, DateTimeKind.Unspecified),
                            PaidAmount = 171m
                        },
                        new
                        {
                            Id = new Guid("f67412b7-509c-4fd4-b4bc-9060bbdb9837"),
                            ConsumptionAmount = 43m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 10, 15, 13, 7, 25, 0, DateTimeKind.Unspecified),
                            PaidAmount = 99m
                        },
                        new
                        {
                            Id = new Guid("a375f6e4-7449-44fe-a8be-59674da1471f"),
                            ConsumptionAmount = 51m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 11, 11, 11, 6, 50, 0, DateTimeKind.Unspecified),
                            PaidAmount = 138.58m
                        },
                        new
                        {
                            Id = new Guid("c93d9609-9738-4be2-aeff-4680509b8ce5"),
                            ConsumptionAmount = 286m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 11, 19, 9, 36, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 193.56m
                        },
                        new
                        {
                            Id = new Guid("c4889e45-998a-41c5-8838-f14513ba73a5"),
                            ConsumptionAmount = 177m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2019, 12, 11, 14, 20, 24, 0, DateTimeKind.Unspecified),
                            PaidAmount = 348.87m
                        },
                        new
                        {
                            Id = new Guid("70bcbbf5-df74-470c-9d5d-5e64a87c69d8"),
                            ConsumptionAmount = 405m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 1, 9, 16, 37, 29, 0, DateTimeKind.Unspecified),
                            PaidAmount = 261.98m
                        },
                        new
                        {
                            Id = new Guid("e87e9d4a-9d14-4b08-ae10-94cab1fdc109"),
                            ConsumptionAmount = 180m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 1, 14, 13, 50, 55, 0, DateTimeKind.Unspecified),
                            PaidAmount = 354m
                        },
                        new
                        {
                            Id = new Guid("582baf39-4c01-4b08-b68b-9cecb886e1a9"),
                            ConsumptionAmount = 202m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 2, 12, 15, 14, 11, 0, DateTimeKind.Unspecified),
                            PaidAmount = 388m
                        },
                        new
                        {
                            Id = new Guid("3c8dc334-8d85-4d53-b6c2-005233596a7c"),
                            ConsumptionAmount = 171m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 3, 13, 13, 55, 33, 0, DateTimeKind.Unspecified),
                            PaidAmount = 330m
                        },
                        new
                        {
                            Id = new Guid("5ca8d0a8-02d7-4964-9a64-73a773ad102f"),
                            ConsumptionAmount = 610m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 3, 17, 13, 46, 23, 0, DateTimeKind.Unspecified),
                            PaidAmount = 409m
                        },
                        new
                        {
                            Id = new Guid("6422be1e-25f5-43ef-b04f-86a9a7de0899"),
                            ConsumptionAmount = 120m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 4, 15, 16, 35, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 239.15m
                        },
                        new
                        {
                            Id = new Guid("78f0061a-ee2c-473f-a9dc-f71e83b244d0"),
                            ConsumptionAmount = 43m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 5, 13, 14, 19, 45, 0, DateTimeKind.Unspecified),
                            PaidAmount = 99.66m
                        },
                        new
                        {
                            Id = new Guid("7ad9e96e-44eb-400f-bfd9-14b5c946c4c3"),
                            ConsumptionAmount = 411m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 5, 13, 14, 22, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 293.21m
                        },
                        new
                        {
                            Id = new Guid("d5e499a2-219d-43bb-8b40-f7e586710220"),
                            ConsumptionAmount = 26m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 6, 15, 13, 13, 37, 0, DateTimeKind.Unspecified),
                            PaidAmount = 68m
                        },
                        new
                        {
                            Id = new Guid("c7c1bd9e-85a5-4dcb-b697-636cccee0db7"),
                            ConsumptionAmount = 376m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 7, 14, 11, 43, 59, 0, DateTimeKind.Unspecified),
                            PaidAmount = 270m
                        },
                        new
                        {
                            Id = new Guid("f6331288-090e-4203-8d90-fdb63d75cd16"),
                            ConsumptionAmount = 15m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 7, 14, 16, 43, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 47m
                        },
                        new
                        {
                            Id = new Guid("a41d5ad4-9585-45df-bcff-0b72d4d1e5c8"),
                            ConsumptionAmount = 14m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 8, 14, 12, 18, 7, 0, DateTimeKind.Unspecified),
                            PaidAmount = 45m
                        },
                        new
                        {
                            Id = new Guid("6a5003ab-529f-4bca-83c8-983dd146c12e"),
                            ConsumptionAmount = 381m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 9, 9, 9, 20, 5, 0, DateTimeKind.Unspecified),
                            PaidAmount = 273.24m
                        },
                        new
                        {
                            Id = new Guid("36798cd9-7497-4611-b58c-9889bf54d136"),
                            ConsumptionAmount = 30m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 9, 30, 15, 28, 29, 0, DateTimeKind.Unspecified),
                            PaidAmount = 77.55m
                        },
                        new
                        {
                            Id = new Guid("309e724c-af98-4489-93de-006819f3da6a"),
                            ConsumptionAmount = 19m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 10, 21, 19, 46, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 47.18m
                        },
                        new
                        {
                            Id = new Guid("84c8a5a1-0df7-46d3-8b28-fc7e1b5e1b53"),
                            ConsumptionAmount = 474m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 11, 6, 7, 34, 13, 0, DateTimeKind.Unspecified),
                            PaidAmount = 332.81m
                        },
                        new
                        {
                            Id = new Guid("4bccda4f-ee8b-4a9b-9225-b320299d1a5f"),
                            ConsumptionAmount = 129m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 11, 17, 15, 27, 21, 0, DateTimeKind.Unspecified),
                            PaidAmount = 240m
                        },
                        new
                        {
                            Id = new Guid("a94a2043-c949-4c80-8053-e1329850314d"),
                            ConsumptionAmount = 156m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2020, 12, 17, 16, 49, 6, 0, DateTimeKind.Unspecified),
                            PaidAmount = 282.76m
                        },
                        new
                        {
                            Id = new Guid("c23154d3-1b41-470c-8e42-a959a9a66eed"),
                            ConsumptionAmount = 668m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 1, 15, 21, 42, 42, 0, DateTimeKind.Unspecified),
                            PaidAmount = 490m
                        },
                        new
                        {
                            Id = new Guid("b06d49d5-e650-49e5-91b9-d233825d9534"),
                            ConsumptionAmount = 193m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 1, 18, 22, 35, 50, 0, DateTimeKind.Unspecified),
                            PaidAmount = 343m
                        },
                        new
                        {
                            Id = new Guid("615ccd8f-fc37-4ca1-87f9-c4ba18e455f6"),
                            ConsumptionAmount = 231m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 2, 16, 14, 13, 9, 0, DateTimeKind.Unspecified),
                            PaidAmount = 401.13m
                        },
                        new
                        {
                            Id = new Guid("121d68d3-7906-464a-8821-7d2f43432b86"),
                            ConsumptionAmount = 613m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 3, 11, 17, 23, 40, 0, DateTimeKind.Unspecified),
                            PaidAmount = 452.38m
                        },
                        new
                        {
                            Id = new Guid("9db6f0ea-fc1e-45c1-82dc-f5127dc568ea"),
                            ConsumptionAmount = 176m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 3, 17, 19, 36, 57, 0, DateTimeKind.Unspecified),
                            PaidAmount = 311m
                        },
                        new
                        {
                            Id = new Guid("730c1eab-fcab-4572-a5d6-86be451b3e80"),
                            ConsumptionAmount = 140m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 4, 16, 19, 9, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 250m
                        },
                        new
                        {
                            Id = new Guid("d6f2caa2-c10f-4feb-98d7-14d073184936"),
                            ConsumptionAmount = 550m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 5, 11, 22, 21, 8, 0, DateTimeKind.Unspecified),
                            PaidAmount = 410m
                        },
                        new
                        {
                            Id = new Guid("80cfed47-c018-47f9-87be-991c8c156852"),
                            ConsumptionAmount = 91m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 5, 14, 6, 44, 10, 0, DateTimeKind.Unspecified),
                            PaidAmount = 193m
                        },
                        new
                        {
                            Id = new Guid("7070ef32-7693-4c0a-8d69-15a5b7eb97cb"),
                            ConsumptionAmount = 29m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 6, 16, 17, 38, 39, 0, DateTimeKind.Unspecified),
                            PaidAmount = 70.79m
                        },
                        new
                        {
                            Id = new Guid("9bb87fa2-24a9-4d91-ace8-24dd1e7ef579"),
                            ConsumptionAmount = 321m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 7, 12, 19, 21, 30, 0, DateTimeKind.Unspecified),
                            PaidAmount = 266.71m
                        },
                        new
                        {
                            Id = new Guid("d407edf7-151e-4602-9a15-b4c4a1bc6da4"),
                            ConsumptionAmount = 18m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 7, 14, 20, 38, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 51.97m
                        },
                        new
                        {
                            Id = new Guid("7e6378fc-3bb5-40b8-91d5-655bb59b2b90"),
                            ConsumptionAmount = 18m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 8, 17, 10, 8, 26, 0, DateTimeKind.Unspecified),
                            PaidAmount = 52.55m
                        },
                        new
                        {
                            Id = new Guid("724d121c-de99-4ef2-ab5c-be6ac4368f0c"),
                            ConsumptionAmount = 356m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 9, 9, 21, 29, 21, 0, DateTimeKind.Unspecified),
                            PaidAmount = 285m
                        },
                        new
                        {
                            Id = new Guid("f103b037-f522-41d0-ae16-21357f3d7c6d"),
                            ConsumptionAmount = 77m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 10, 20, 17, 27, 53, 0, DateTimeKind.Unspecified),
                            PaidAmount = 168m
                        },
                        new
                        {
                            Id = new Guid("c6b1b113-a204-4225-8254-0f7cf8b5f2bb"),
                            ConsumptionAmount = 413m,
                            ConsumptionTypeId = new Guid("251fb0f9-1632-485b-9a10-22e901253c73"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 11, 6, 15, 41, 24, 0, DateTimeKind.Unspecified),
                            PaidAmount = 321.84m
                        },
                        new
                        {
                            Id = new Guid("c45136c2-c016-4eb6-a21c-6ee16dc8c449"),
                            ConsumptionAmount = 20m,
                            ConsumptionTypeId = new Guid("f6eb3f75-7afb-4577-bf62-5ea66e69acd8"),
                            Currency = 0,
                            OccuredAt = new DateTime(2021, 9, 10, 15, 55, 44, 0, DateTimeKind.Unspecified),
                            PaidAmount = 58.35m
                        });
                });

            modelBuilder.Entity("FinApp.Api.Models.Expense", b =>
                {
                    b.HasOne("FinApp.Api.Models.ConsumptionType", "ConsumptionType")
                        .WithMany()
                        .HasForeignKey("ConsumptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumptionType");
                });
#pragma warning restore 612, 618
        }
    }
}
